### ISSUE TITLE
TypeError: 'property' object is not callable for f, f_hat and x setters

### ISSUE THREAD

**Issue by ghisvail** [pyNFFT/pyNFFT#14]
Using the following property setter notation:

``` python
plan.f = some_f
# or
plan.f_hat = some_f_hat
# or
plan.x = some_x
```

triggers a TypeError: 'property' object is not callable, due to the current implementation of properties not using [Cython's custom syntax](http://docs.cython.org/src/reference/extension_types.html).

**Comment by yiboyang** [comment]
For anybody still experiencing this: updating my Cython installation from 0.23.4 to 0.25.2 solved the problem.
